### PR TITLE
Moving Discord Bot Token and Guild ID to server side and redoing some basic stuff.

### PR DESCRIPTION
**Pull request by Ruby-LK**
This pull request ensures that client modders/dumpers won't have access to the bot token because it has been moved from the config to the server side
Edit : Changed the notification function to event,

### CODE REVIEW

**Comment by lenzh** [comment]
way better doing this! this needs to be merged

**Comment by boppescripting** [comment]
Hey... thanks for the pull request! I have a couple questions...

1. Why are we moving the token and server id to the server-side file? The config is only loaded on the server-side regardless in the fxmanifest so the client has no access to it.

2. Is switching from the notify function to the event for backwards-compatibility with older versions of qb-core?

**Comment by Ruby-LK** [comment]
Hello there, Thanks for the response.

01. Just noticed that config is loading in server side. So that 2 changes not required at all. 
02. Yes made that change for the backwards-compatibility with older versions of qb-core cuz some versions didn't work with the function. I had some scripts in my previous servers with the same but didn't work well because of the same thing. Will test more to confirm.

Thanks for your response again.

**Comment by Ruby-LK** [comment]
Hello again,
Did some search on previous versions of qb-core and confirmed that current versions has the compatibility for the function. So both changes are not required.

So can close this now.
Thanks again for the response.

**Pull request closed without merging**
